# docker-compose.yml
version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: app.container/Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST} remote_port=${XDEBUG_PORT}"
        volumes:
            - ./:/var/www
    web:
        build:
            context: ./
            dockerfile: web.container/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "${WEB_PORT}:80"
        links:
            - app